# Generated by Django 5.2.3 on 2025-06-23 08:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bom', '0001_initial'),
        ('parts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bomitem',
            name='child',
            field=models.ForeignKey(help_text='Component that is part of the assembly', on_delete=django.db.models.deletion.CASCADE, related_name='bom_child', to='parts.part'),
        ),
        migrations.AlterField(
            model_name='bomitem',
            name='parent',
            field=models.ForeignKey(help_text='The main part (assembly)', on_delete=django.db.models.deletion.CASCADE, related_name='bom_parent', to='parts.part'),
        ),
        migrations.AlterUniqueTogether(
            name='bomitem',
            unique_together={('parent', 'child')},
        ),
    ]
